local GoldemShopItens = {
    [150] = {
        titleTop = "150 Robux",
        ItenImgID = "rbxassetid://17748694278",
        ItenName = "100 Golden Botton",
        BonusText = "0 Bonus golden botton"
    },
    [500] = {
        titleTop = "500 Robux",
        ItenImgID = "rbxassetid://17748855355",
        ItenName = "500 Golden Botton",
        BonusText = "100 Bonus golden bottom"
    },
    [850] = {
        titleTop = "850 Robux",
        ItenImgID = "rbxassetid://17748859655",
        ItenName = "1500 Golden Botton",
        BonusText = "250 Bonus golden bottom"
    },
    [1500] = {
        titleTop = "1500 Robux",
        ItenImgID = "rbxassetid://17748862877",
        ItenName = "2500 Golden Botton",
        BonusText = "500 Bonus golden bottom"
    },
}

return GoldemShopItens