local GoldemShopItens = { -- Lista de itens de compra de botões dourados para a guia de compra de botões
    [100] = {
        titleTop = "150 Robux",
        ItenImgID = "rbxassetid://17748694278",
        ItenName = "100 Golden Botton",
        BonusText = "0 Bonus golden botton",
        ProductDeveloper = "1845872803"
    },
    [500] = {
        titleTop = "500 Robux",
        ItenImgID = "rbxassetid://17748855355",
        ItenName = "500 Golden Botton",
        BonusText = "100 Bonus golden bottom",
        ProductDeveloper = "1845882822"
    },
    [850] = {
        titleTop = "850 Robux",
        ItenImgID = "rbxassetid://17748859655",
        ItenName = "1500 Golden Botton",
        BonusText = "250 Bonus golden bottom",
        ProductDeveloper = "1845884418"
    },
    [1500] = {
        titleTop = "1500 Robux",
        ItenImgID = "rbxassetid://17748862877",
        ItenName = "2500 Golden Botton",
        BonusText = "500 Bonus golden bottom",
        ProductDeveloper = "1845886313"
    },
}

return GoldemShopItens