local MissionWeekList = "returns"
--
--    [1] = {
--        Name = "Mission Name 1",
--        Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
--        Recompenses = { { IMG = "img", RECOMPENSE_NAME = "First Recompense",}, { IMG = "", RECOMPENSE_NAME = "Second Recompense"}, },
--    },
--
--    [2] = {
--        Name = "Mission Name 2",
--        Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
--        Recompenses = {{ IMG = "img", RECOMPENSE_NAME = "Second Recompense"}, },
--    },
--
--    [3] = {
--        Name = "Mission Name 3",
--        Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
--        Recompenses = { { IMG = "img", RECOMPENSE_NAME = "First Recompense"}, { IMG = "", RECOMPENSE_NAME = "Second Recompense"}, },
--    },
--}

return MissionWeekList