local UpgradeList: {[string]: string} = {
    [1] = {
        Version = "0.0.3",
        Configs = {
            Title_Version = "Update 0.0.3",
            Name_Version = "The new era",
            Image_Id = "rbxassetid://17627927748",
        },

        Topics = {
            "• Created and added the game's definitive UI",
            "• Add new functions (Purchase gold buttons, hud functionality)",
            "• Created interactive areas (mystery tent, games tent and more)",
            "• Lobby map created and added to the game",
            "• Cumulative updates",
            "• Fix other bugs",
        }
    }
}

return UpgradeList