local UpgradeList: {[string]: string} = {
    ["0.0.1"] = {
        Configs = {
            Title_Version = "Update 0.0.1",
            Name_Version = "The creation",
            Image_Id = "rbxassetid://17627650820",
        }, 
        
        Topics = {
            "• Create Upgrade Gui.",
            "• Fix bug in Screeam gui loaded",
            "• Fix hud sync",
            "• Fix other bugs",
        }
    },

    ["0.0.2"] = {
        Configs = {
            Title_Version = "Update 0.0.2",
            Name_Version = "Appearances can be deceiving",
            Image_Id = "rbxassetid://17627891476",
        },

        Topics = {
            "• Create UI Test Designer.",
            "• Create code service.",
            "• Create game life gui",
            "• Fix other bugs",
            "• Cumulative update"
        }
    },

    ["0.0.3"] = {
        Configs = {
            Title_Version = "Update 0.0.3",
            Name_Version = "A new era",
            Image_Id = "rbxassetid://17627927748",
        },

        Topics = {
            "• Create UI definitive Designer.",
            "• Added new functions.",
            "• Created several markets",
            "• Lobby map added",
            "• Fix other bugs",
            "• Cumulative update"
        }
    }
}

return UpgradeList