local UpgradeList: {[string]: string} = {
    ["0.0.1"] = {
        Title = "Upgrade 0.0.1 - Game Beta",
        Topics = {
            "• Create Upgrade Gui.",
            "• Fix bug in Screeam gui loaded",
            "• Fix hud sync",
            "• Fix other bugs",
        }
    },
    ["0.0.2"] = {
        Title = "Upgrade 0.0.1 - Gui and code upgrade",
        Topics = {
            "• Create UI Designer.",
            "• Create code service.",
            "• Create game life gui",
            "• Fix other bugs",
        }
    }
}

return UpgradeList