local MissionLists = {
    [1] = {
        MissionID = "MISSION_TEST",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [2] = {
        MissionID = "MISSION_TEST2",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [3] = {
        MissionID = "MISSION_TEST3",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [4] = {
        MissionID = "MISSION_TEST4",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [5] = {
        MissionID = "MISSION_TEST5",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [6] = {
        MissionID = "MISSION_TEST6",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [7] = {
        MissionID = "MISSION_TEST7",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

}

return MissionLists