local MissionLists = {
    [1] = {
        MissionID = "MISSION_1",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [2] = {
        MissionID = "MISSION_2",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [3] = {
        MissionID = "MISSION_3",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [4] = {
        MissionID = "MISSION_4",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [5] = {
        MissionID = "MISSION_5",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [6] = {
        MissionID = "MISSION_6",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

    [7] = {
        MissionID = "MISSION_7",
        Recompense = function(player)
            print("Recebeu a recompensa")
        end
    },

}

return MissionLists